site_name: Kumon Math App
repo_url: https://github.com/JangasCodingplace/kumon-math-app
edit_uri: https://github.com/JangasCodingplace/kumon-math-app/blob/main/docs/
nav:
  - Introduction: index.md
  - Getting Started: getting-started.md
  - Developer Tutorial: developer-tutorial.md
  - Contributing: CONTRIBUTING.md
  - License: LICENSE
  - Changelog: CHANGELOG.md
theme: readthedocs
